#Config

defaultSpawn: spawn
spawnOnJoin: true

spawns:
  spawn:
    World: world
    X: 0
    Y: 0
    Z: 0
    Yaw: 0
    Pitch: 0

mysql:
  use: false
  host: 127.0.0.1
  port: 3306
  database: ad
  user: ad
  password: password
