name: AD-Core
version: 1.3.0
author: Tigifan
main: de.apollodoener.core.ApolloDoener
depend: [ADAPI]

commands:
    gamemode:
        description: Aendert deinen Gamemode
        permissions: ad.gamemode
        aliases: [gm]
    heal:
        description: Heilt dich
        permissions: ad.heal
    feed:
        description: Saettigt dich
        permission: ad.feed
    teleport:
        description: Teleportiert dich
        permission: ad.teleport
        aliases: [tp]
    setspawn:
        description: Setzt Spawns
        permission: ad.setspawn
    fly:
        description: Gibt Fly
        permission: ad.fly
    spawn:
        description: Teleportiert dich zum Spawn
        permission: ad.spawn
    back:
        description: Teleportiert dich zu deiner letzten Location
        permission: ad.back
    rank:
        description: Rank Manager
        permission: ad.rank
    filedownload:
        description: Download files into plugins-directory
        permission: ad.download
        aliases: [fdl]
    playerhead:
        description: Gibt dir einen Spielerkopf
        permission: ad.playerhead
        aliases: [ph]
    backup:
        description: Erstellt ein Backup
        permission: ad.backup
        aliases: [adbackup, adbu, bu]

