name: AD-Core
version: 1.0
author: Tigifan
main: de.tigifan.core.bukkit.ADBukkit

commands:
    gamemode:
        description: Aendert deinen Gamemode
        permissions: ad.gamemode
        aliases: [gm]
    heal:
        description: Heilt dich
        permissions: ad.heal
    feed:
        description: Saettigt dich
        permission: ad.feed
